name: Publish and Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "package.json"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Needed for publishing
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          registry-url: "https://npm.pkg.github.com"

      - name: Install Dependencies
        run: npm install

      - name: Build TypeScript and Types
        run: |
          npm run build
          tsc --declaration --emitDeclarationOnly --outDir dist/

      - name: Upload Build Artifacts (JS + TypeScript Types)
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  publish_npm:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write # Needed for publishing to npm

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          registry-url: "https://npm.pkg.github.com"

      - name: Download Built Artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Publish to GitHub Packages
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write # Needed for GitHub Releases

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Built Artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Upload Build Artifacts (JS + TypeScript Types) to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files:
            - dist/*
            - dist/**/*.d.ts
          tag_name: ${{ github.ref_name }}
          body: "Automated release for ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
