name: Publish npm package
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "package.json"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    permissions:
      contents: read
      packages: write # Needed for publishing
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          registry-url: "https://npm.pkg.github.com"

      - name: Install Dependencies
        run: npm install

      - name: Build TypeScript
        run: |
          npm run build
          mkdir dist-release
          mv dist/* dist-release/

      - name: Publish to GitHub Packages
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Build Artifacts to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist-release/*
          tag_name: ${{ github.ref_name }}
          body: "Automated release for ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
